language: ruby
cache:
  directories:
    - bundle

before_install:
  - gem update --system
  - gem install bundler

sudo: false

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

script:
    - bundle exec rake spec
